name: raking
channels:
  - conda-forge
  - defaults
dependencies:
  - altair
  - dash
  - dash-bootstrap-components
  - jupyter
  - line_profiler
  - matplotlib
  - notebook
  - numpy
  - openpyxl
  - pandas
  - pip
  - plotly
  - pyreadr
  - scipy
  - vegafusion>=1.5.0
  - vegafusion-python-embed>=1.5.0
  - vl-convert-python
  - pip:
    - dash-vega-components

